project_id = "zzzhmwwidepbnkwtppqj"

[functions.parse-expense]
verify_jwt = false

[functions.parse-expense-fallback]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.push-register]
verify_jwt = false

[functions.push-send]
verify_jwt = false
