project_id = "zzzhmwwidepbnkwtppqj"

[functions.parse-expense]
verify_jwt = true

[functions.parse-expense-fallback]
verify_jwt = true

[functions.process-receipt]
verify_jwt = true

[functions.process-pdf-text]
verify_jwt = false

[functions.push-register]
verify_jwt = false

[functions.push-send]
verify_jwt = false
